server:
  port: 0

spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
